/*
 * This file is generated by jOOQ.
 */
package com.boxfox.calendar.database;


import com.boxfox.calendar.database.tables.Task;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.task</code>.
     */
    public static final Task TASK = com.boxfox.calendar.database.tables.Task.TASK;
}
